[versions]
agp = "8.3.0-alpha07"
android-material = "1.10.0"
androidx-navigation = "2.7.4"
androidx-test-espresso = "3.6.0-alpha01"
build-android-compileSdk = "34"
build-android-minSdk = "21"
build-android-targetSdk = "34"
build-javaVersion = "VERSION_17"
build-jvmTarget = "17"
detekt = "1.23.1"
kotlin = "1.9.10"
kotlinx-kover = "0.7.4"

[libraries]
android-material = { module = "com.google.android.material:material", version.ref = "android-material" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlinx-kover" }
