name: Android tests

on: [ push ]

jobs:

  Device:
    # runs-on: ${{ matrix.os }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        # os: [ macos-latest, ubuntu-latest ]
        managed-virtual-devicel: [
          29,
          29_64Bit,
          30,
          30_64Bit,
          31,
          31_64Bit,
          32,
          32_64Bit,
          33,
          33_64Bit,
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: bash ./gradlew managedVirtualDevice${{ matrix.managed-virtual-devicel }}Check --stacktrace

