name: Android build

on: [ push ]

jobs:


  jobBuild:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'

      - run: bash ./gradlew clean ktlintCheck lint testDebugUnitTest build --stacktrace
