name: Android build

on: [ push ]

jobs:

  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [ self-hosted, macos-latest, ubuntu-latest, windows-latest ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
        if: ${{ matrix.os != 'self-hosted' }}

      - uses: android-actions/setup-android@v2

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: ciBuildAll --stacktrace

  Device:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #        os: [ self-hosted, macos-latest ]
        os: [ macos-latest ]
        managed-virtual-devicel: [ 29, 30, 31, 32, 33 ]
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
        if: ${{ matrix.os != 'self-hosted' }}

      - uses: android-actions/setup-android@v2

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: managedVirtualDevice${{ matrix.managed-virtual-devicel }}Check -Pandroid.testInstrumentationRunnerArguments.class=siarhei.luskanau.managed.virtual.device.ExampleInstrumentedTest -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect --stacktrace
