name: Android tests

on: [ push ]

jobs:

  AndroidTests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        android-api-level: [ 24, 28 ]

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'

      - uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.android-api-level }}
          target: default
          arch: x86
          profile: Nexus 6
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: ./gradlew connectedAndroidTest
