name: Android build

on: [ push ]

jobs:

  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [ self-hosted, macos-latest, ubuntu-latest, windows-latest ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
        if: ${{ matrix.os != 'self-hosted' }}

      - uses: android-actions/setup-android@v2

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: ciBuildAll --stacktrace
